# Generated by Django 4.1.7 on 2023-08-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teacher_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('بكالوريا', 'بكالوريا'), ('تاسع', 'تاسع')], max_length=50),
        ),
    ]
