# Generated by Django 4.1.7 on 2023-08-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='course',
            name='number_of_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
