# Generated by Django 4.1.7 on 2023-08-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_max_students_course_number_of_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
