# Generated by Django 4.1.7 on 2023-08-19 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_course_class_course_level'),
        ('api', '0005_course_picture'),
    ]

    operations = [
    ]
